language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "stable"
cache:
    directories:
    - node_modules
deploy:
  provider: script
  script: npm install && npm run deploy
  on:
    branch: develop